version: "3.1"
services:
    mongodb:
        image: mongo
        ports:
            - "27017:27017"
        restart: always
        volumes:
            - "./setup:/setup"
    
            
